### ISSUE TITLE
Handle on chain payouts tracking

### ISSUE THREAD

**Issue by sandoche** [NEARWEEK/api.grants#5]
- [x] Check how it is handled in Sputnik DAO code
- [x] Fix bug of salt changing by itself
- [x] Fix display of payments
- [x] Mark the dateFirstPayment done as done if it is
